### ISSUE TITLE
文章开头的 tag 是只显示英文吗

### ISSUE THREAD

**Issue by RocFang** [yanlinlin82/simple-style#1]
@yanlinlin82 Hi, 您好：）

每篇文章页面的开头，正常是会显示用 # 开头的 tag 列表的，但是经过测试我发现如果 tag 是中文的话，就不显示了。

在您自己的博客上，我也找到了类似的，例如，https://yanlinlin.cn/2007/08/05/hello-world/
这一篇里面有 “博客” tag，但是也没显示。

不知道这个是否是正常的？

**Comment by yanlinlin82** [comment]
谢谢反馈！我检查下。

**Comment by yanlinlin82** [comment]
已在最新版本（[f6b06d2](https://github.com/yanlinlin82/simple-style/tree/f6b06d215f42d08a9f224954c9d8c4498c3449f7)）修复。再次感谢关注和反馈！

**Comment by RocFang** [comment]
@yanlinlin82 高效，赞！
