### ISSUE TITLE
在底部添加一下您这个主题的链接？

### ISSUE THREAD

**Issue by RocFang** [yanlinlin82/simple-style#2]
@yanlinlin82 hi，您好，用了您这个主题一段时间了，很喜欢。谢谢！
但是您这个主题底部不像一般主题一样有自己的相关链接，加一个的话也可以让更多的人知道这个主题哈。

**Comment by yanlinlin82** [comment]
谢谢支持！我尝试加一下。

**Comment by yanlinlin82** [comment]
我增加了一个配置项（在config.toml中）：

```
[params]
ShowThemeInfo = true
```

在没有该选项时，缺省是不增加主题链接的，这样能保持内容尽量简洁（不干扰用户）。若打开该选项，其效果如下图所示（版权文字信息的下面，追加了一行）：

![image](https://user-images.githubusercontent.com/2879428/77439721-5b6c7780-6e22-11ea-9af2-a283fc5eff3b.png)

再次感谢您的支持，以及提出这个建议！如有其他需求，也随时欢迎提出，我会尽量设法改进和实现。

**Comment by RocFang** [comment]
赞！已更新：）
